version: "2.2"
services:
  web:
    build: 
      context: .
    container_name: prolibu_feed
    command: npm run serve
    volumes: 
      - ./code:/code
    ports:
      - 3003:3003
volumes:
  code: {}

